In [1]:
import numpy as np
import pandas as pd
import matplotlib
import json
from sklearn.cluster import KMeans
%matplotlib inline

In [3]:
df_appliances = pd.read_csv('credit_card/appliances.csv')
df_department = pd.read_csv('credit_card/departmentstore.csv')
df_drug = pd.read_csv('credit_card/drug.csv')
df_fashion = pd.read_csv('credit_card/fashion.csv')
df_flower = pd.read_csv('credit_card/flowershop.csv')
df_food = pd.read_csv('credit_card/food.csv')
df_home = pd.read_csv('credit_card/home_goods.csv')
df_luxury = pd.read_csv('credit_card/luxury.csv')
df_reuse = pd.read_csv('credit_card/reuse.csv')
df_sport = pd.read_csv('credit_card/sport.csv')
df_super = pd.read_csv('credit_card/supermarket.csv')

In [4]:
df_appliances.head()

month   アメリカ合衆国   オーストラリア         台湾    中華人民共和国         タイ         香港  \
0  12-Aug  49171922  26340071   94590771  156240871   60798441   66252524   
1  12-Sep  55425553  36140241   97834288   84001724   88439712   75978641   
2  12-Oct  56629758  40049371  103367812   69291641  157488912   78040706   
3  12-Nov  47490087  41192971  163181941   59520106  116607376   82751224   
4  12-Dec  63525540  58901488  155653129   92870059  177378524  120890276   

        大韓民国    シンガポール  
0   83092041  27492894  
1   87631229  29091741  
2   93480094  53054012  
3  121145265  63097565  
4  122495218  99181071

In [5]:
df_appliances['台湾'].values

array([  94590771,   97834288,  103367812,  163181941,  155653129,
        190887224,  295630618,  367051488,  508157906,  573145682,
        495434847,  402260500,  298226471,  390051118,  325691547,
        533125241,  897358412,  794930553,  621988273,  641420173,
        619585040,  534832173,  531404300,  594699233,  501712940,
        554407933,  997238873, 1466322947, 1547160717, 1471211833,
       1785200453, 1768208120, 2465563487, 2375592347, 3339225227,
       3240584260, 2955352420, 2436377055, 2821861700, 2740272370,
       2568158907, 2508766838, 2409342010, 1590571234])

In [6]:
length = len(df_appliances['台湾'].values)

In [7]:
# 1月あたり旅行者
tourlist_dic={}
for year in range(2012,2017):
    with open("tourists_number/FY%d"%year,"r",encoding="utf-8") as f:
        dic = json.load(f)
    for countryData in dic["result"]["changes"]:
        country = countryData["countryName"]
        for i in range(len(countryData["data"])):
            num_qt = countryData["data"][i]
            if num_qt["year"] == year:
                if year == 2012:
                    if num_qt["quarter"] > 2:
                        if num_qt["quarter"] == 3:
                            iteration = 2
                        elif num_qt["quarter"] == 4:
                            iteration = 3
                        num_m = num_qt["value"]/3
                        for i in range(iteration):
                            try:
                                tourlist_dic[country].append(num_m)
                            except:
                                tourlist_dic[country] = [num_m]
                elif year == 2016:
                    if num_qt["quarter"] == 1:
                        num_m = num_qt["value"]/3
                        for i in range(3):
                            try:
                                tourlist_dic[country].append(num_m)
                            except:
                                tourlist_dic[country] = [num_m]
                else:
                    num_m = num_qt["value"]/3
                    for i in range(3):
                        try:
                            tourlist_dic[country].append(num_m)
                        except:
                            tourlist_dic[country] = [num_m]
for k,v in tourlist_dic.items():
    tourlist_dic[k] = np.array(v)


In [8]:
tourlist_dic['台湾']

array([  60282.        ,   60282.        ,   47251.        ,
         47251.        ,   47251.        ,   50771.66666667,
         50771.66666667,   50771.66666667,   75715.33333333,
         75715.33333333,   75715.33333333,   85122.66666667,
         85122.66666667,   85122.66666667,   64330.        ,
         64330.        ,   64330.        ,   79218.66666667,
         79218.66666667,   79218.66666667,  100437.66666667,
        100437.66666667,  100437.66666667,  100593.66666667,
        100593.66666667,  100593.66666667,   87058.33333333,
         87058.33333333,   87058.33333333,  102430.        ,
        102430.        ,  102430.        ,  124405.33333333,
        124405.33333333,  124405.33333333,  118414.33333333,
        118414.33333333,  118414.33333333,  100467.66666667,
        100467.66666667,  100467.66666667,  121293.        ,
        121293.        ,  121293.        ])

In [9]:
c_list = ['アメリカ合衆国', 'オーストラリア', '中華人民共和国', '台湾', '大韓民国', '香港', 'タイ', 'シンガポール']
appliances_sum = np.zeros(length)
tourist_sum = np.zeros(length)
for c in c_list:
    appliances_sum += df_appliances[c].values
    tourist_sum += tourlist_dic[c]

In [10]:
appliances_sum

array([  5.63979535e+08,   5.54543129e+08,   6.51402306e+08,
         6.94986535e+08,   8.90895305e+08,   9.05163197e+08,
         1.13848683e+09,   1.52224248e+09,   1.99802632e+09,
         1.88549215e+09,   1.59372622e+09,   1.62010248e+09,
         1.30164385e+09,   1.38817901e+09,   1.47591447e+09,
         1.72749464e+09,   2.23829160e+09,   2.22276024e+09,
         1.95632987e+09,   2.31276091e+09,   2.67365282e+09,
         2.09661896e+09,   1.85742532e+09,   2.39739505e+09,
         2.08351000e+09,   2.44367221e+09,   3.69483550e+09,
         4.66420544e+09,   5.22091481e+09,   4.74479193e+09,
         6.45151465e+09,   6.95242782e+09,   9.23295603e+09,
         7.04673065e+09,   7.54826371e+09,   9.07512082e+09,
         8.39353595e+09,   5.69655496e+09,   7.56515770e+09,
         7.00856920e+09,   6.61320618e+09,   6.00522637e+09,
         5.71504977e+09,   1.71154261e+10])