In [1]:
import numpy as np
import pandas as pd
import matplotlib
import json
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
%matplotlib inline

In [2]:
df_appliances = pd.read_csv('credit_card/appliances.csv',index_col="month")
df_department = pd.read_csv('credit_card/departmentstore.csv',index_col="month")
df_drug = pd.read_csv('credit_card/drug.csv',index_col="month")
df_fashion = pd.read_csv('credit_card/fashion.csv',index_col="month")
df_flower = pd.read_csv('credit_card/flowershop.csv',index_col="month")
df_food = pd.read_csv('credit_card/food.csv',index_col="month")
df_home = pd.read_csv('credit_card/home_goods.csv',index_col="month")
df_luxury = pd.read_csv('credit_card/luxury.csv',index_col="month")
df_reuse = pd.read_csv('credit_card/reuse.csv',index_col="month")
df_sport = pd.read_csv('credit_card/sport.csv',index_col="month")
df_super = pd.read_csv('credit_card/supermarket.csv',index_col="month")

In [17]:
df_appliances.head()

アメリカ合衆国    オーストラリア    中華人民共和国        大韓民国          台湾          香港  \
month                                                                         
Aug-12  450977581  171900635  967068187   907359112  1024873519   785449686   
Sep-12  482890702  232713382  629385071  1003537082   972290417   721586084   
Oct-12  573490536  246991846  619997765  1200882541  1047116686   911434209   
Nov-12  554981840  216140159  595937535  1213589600  1205606620   972991674   
Dec-12  688458547  333476482  760322171  1292732394  1259938330  1123123556   

                タイ     シンガポール  
month                          
Aug-12   665674228  313876677  
Sep-12   732925900  339416355  
Oct-12  1219434142  410577940  
Nov-12   826646261  589694787  
Dec-12  1344977827  885657320

In [3]:
df_appliances = pd.read_csv('credit_card/appliances.csv')
df_department = pd.read_csv('credit_card/departmentstore.csv')
df_drug = pd.read_csv('credit_card/drug.csv')
df_fashion = pd.read_csv('credit_card/fashion.csv')
df_flower = pd.read_csv('credit_card/flowershop.csv')
df_food = pd.read_csv('credit_card/food.csv')
df_home = pd.read_csv('credit_card/home_goods.csv')
df_luxury = pd.read_csv('credit_card/luxury.csv')
df_reuse = pd.read_csv('credit_card/reuse.csv')
df_sport = pd.read_csv('credit_card/sport.csv')
df_super = pd.read_csv('credit_card/supermarket.csv')

In [4]:
df_appliances.head()

month   アメリカ合衆国   オーストラリア         台湾    中華人民共和国         タイ         香港  \
0  12-Aug  49171922  26340071   94590771  156240871   60798441   66252524   
1  12-Sep  55425553  36140241   97834288   84001724   88439712   75978641   
2  12-Oct  56629758  40049371  103367812   69291641  157488912   78040706   
3  12-Nov  47490087  41192971  163181941   59520106  116607376   82751224   
4  12-Dec  63525540  58901488  155653129   92870059  177378524  120890276   

        大韓民国    シンガポール  
0   83092041  27492894  
1   87631229  29091741  
2   93480094  53054012  
3  121145265  63097565  
4  122495218  99181071

In [12]:
df_department.head()

month    アメリカ合衆国    オーストラリア    中華人民共和国        大韓民国          台湾  \
0  Aug-12  450977581  171900635  967068187   907359112  1024873519   
1  Sep-12  482890702  232713382  629385071  1003537082   972290417   
2  Oct-12  573490536  246991846  619997765  1200882541  1047116686   
3  Nov-12  554981840  216140159  595937535  1213589600  1205606620   
4  Dec-12  688458547  333476482  760322171  1292732394  1259938330   

           香港          タイ     シンガポール  
0   785449686   665674228  313876677  
1   721586084   732925900  339416355  
2   911434209  1219434142  410577940  
3   972991674   826646261  589694787  
4  1123123556  1344977827  885657320

In [10]:
pd.merge(df_appliances, df_department,on="month")

Empty DataFrame
Columns: [month, アメリカ合衆国_x, オーストラリア_x, 台湾_x, 中華人民共和国_x, タイ_x, 香港_x, 大韓民国_x, シンガポール_x, アメリカ合衆国_y, オーストラリア_y, 中華人民共和国_y, 大韓民国_y, 台湾_y, 香港_y, タイ_y, シンガポール_y]
Index: []

In [4]:
df_appliances['台湾'].values

array([  94590771,   97834288,  103367812,  163181941,  155653129,
        190887224,  295630618,  367051488,  508157906,  573145682,
        495434847,  402260500,  298226471,  390051118,  325691547,
        533125241,  897358412,  794930553,  621988273,  641420173,
        619585040,  534832173,  531404300,  594699233,  501712940,
        554407933,  997238873, 1466322947, 1547160717, 1471211833,
       1785200453, 1768208120, 2465563487, 2375592347, 3339225227,
       3240584260, 2955352420, 2436377055, 2821861700, 2740272370,
       2568158907, 2508766838, 2409342010, 1590571234])

In [5]:
length = len(df_appliances['台湾'].values)
print(length)

44


In [6]:
usa_df = pd.DataFrame()
usa_df["appliance"] = df_appliances["アメリカ合衆国"]
usa_df["department"] = df_department["アメリカ合衆国"]
usa_df["drug"] = df_drug["アメリカ合衆国"]
usa_df["fashion"] = df_fashion["アメリカ合衆国"]
usa_df["flower"] = df_flower["アメリカ合衆国"]
usa_df["food"] = df_food["アメリカ合衆国"]
usa_df["home"] = df_home["アメリカ合衆国"]
usa_df["luxury"] = df_luxury["アメリカ合衆国"]
usa_df["reuse"] = df_reuse["アメリカ合衆国"]
usa_df["sport"] = df_sport["アメリカ合衆国"]
usa_df["super"] = df_super["アメリカ合衆国"]

In [7]:
usa_df.head()

appliance  department  drug  fashion  flower  food  home  luxury  \
month                                                                      
12-Aug   49171922         NaN   NaN      NaN     NaN   NaN   NaN     NaN   
12-Sep   55425553         NaN   NaN      NaN     NaN   NaN   NaN     NaN   
12-Oct   56629758         NaN   NaN      NaN     NaN   NaN   NaN     NaN   
12-Nov   47490087         NaN   NaN      NaN     NaN   NaN   NaN     NaN   
12-Dec   63525540         NaN   NaN      NaN     NaN   NaN   NaN     NaN   

        reuse  sport  super  
month                        
12-Aug    NaN    NaN    NaN  
12-Sep    NaN    NaN    NaN  
12-Oct    NaN    NaN    NaN  
12-Nov    NaN    NaN    NaN  
12-Dec    NaN    NaN    NaN

In [14]:
# 1月あたり旅行者
tourlist_dic={}
for year in range(2012,2017):
    with open("tourists_number/FY%d"%year,"r",encoding="utf-8") as f:
        dic = json.load(f)
    for countryData in dic["result"]["changes"]:
        country = countryData["countryName"]
        for i in range(len(countryData["data"])):
            num_qt = countryData["data"][i]
            if num_qt["year"] == year:
                if year == 2012:
                    if num_qt["quarter"] > 2:
                        if num_qt["quarter"] == 3:
                            iteration = 2
                        elif num_qt["quarter"] == 4:
                            iteration = 3
                        num_m = num_qt["value"]/3
                        for i in range(iteration):
                            try:
                                tourlist_dic[country].append(num_m)
                            except:
                                tourlist_dic[country] = [num_m]
                elif year == 2016:
                    if num_qt["quarter"] == 1:
                        num_m = num_qt["value"]/3
                        for i in range(3):
                            try:
                                tourlist_dic[country].append(num_m)
                            except:
                                tourlist_dic[country] = [num_m]
                else:
                    num_m = num_qt["value"]/3
                    for i in range(3):
                        try:
                            tourlist_dic[country].append(num_m)
                        except:
                            tourlist_dic[country] = [num_m]
for k,v in tourlist_dic.items():
    tourlist_dic[k] = np.array(v)


In [17]:
tourlist_num = pd.DataFrame()
c_list = ['アメリカ合衆国', 'オーストラリア', '中華人民共和国', '台湾', '大韓民国', '香港', 'タイ', 'シンガポール']
for i in c_list:
    tourlist_num[i] = tourlist_dic[i]

In [18]:
tourlist_num.head()

アメリカ合衆国       オーストラリア        中華人民共和国       台湾          大韓民国  \
0  32372.666667  11410.666667  108908.333333  60282.0  64795.333333   
1  32372.666667  11410.666667  108908.333333  60282.0  64795.333333   
2  39051.000000  14546.666667   25528.666667  47251.0  60948.333333   
3  39051.000000  14546.666667   25528.666667  47251.0  60948.333333   
4  39051.000000  14546.666667   25528.666667  47251.0  60948.333333   

             香港            タイ        シンガポール  
0  22080.666667   7572.666667   5277.666667  
1  22080.666667   7572.666667   5277.666667  
2  21171.000000  15862.000000  11886.333333  
3  21171.000000  15862.000000  11886.333333  
4  21171.000000  15862.000000  11886.333333

In [8]:
# 国籍をつぶす場合
c_list = ['アメリカ合衆国', 'オーストラリア', '中華人民共和国', '台湾', '大韓民国', '香港', 'タイ', 'シンガポール']
appliances_sum = np.zeros(length)
tourlist_sum = np.zeros(length)
for c in c_list:
    appliances_sum += df_appliances[c].values
    tourlist_sum += tourlist_dic[c]

In [9]:
appliances_sum

array([  5.63979535e+08,   5.54543129e+08,   6.51402306e+08,
         6.94986535e+08,   8.90895305e+08,   9.05163197e+08,
         1.13848683e+09,   1.52224248e+09,   1.99802632e+09,
         1.88549215e+09,   1.59372622e+09,   1.62010248e+09,
         1.30164385e+09,   1.38817901e+09,   1.47591447e+09,
         1.72749464e+09,   2.23829160e+09,   2.22276024e+09,
         1.95632987e+09,   2.31276091e+09,   2.67365282e+09,
         2.09661896e+09,   1.85742532e+09,   2.39739505e+09,
         2.08351000e+09,   2.44367221e+09,   3.69483550e+09,
         4.66420544e+09,   5.22091481e+09,   4.74479193e+09,
         6.45151465e+09,   6.95242782e+09,   9.23295603e+09,
         7.04673065e+09,   7.54826371e+09,   9.07512082e+09,
         8.39353595e+09,   5.69655496e+09,   7.56515770e+09,
         7.00856920e+09,   6.61320618e+09,   6.00522637e+09,
         5.71504977e+09,   1.71154261e+10])

In [14]:
X = df_appliances

In [25]:
X = X/tourlist_num

In [26]:
X.head()

Unnamed: 0       アメリカ合衆国       オーストラリア        シンガポール            タイ  \
0        NaN  13930.813474  15064.907251  59472.622434  87904.863280   
1        NaN  14916.617990  20394.372108  64311.821196  96785.707369   
2        NaN  14685.681186  16979.274473  34542.018004  76877.704073   
3        NaN  14211.719034  14858.397731  49611.160184  52114.882171   
4        NaN  17629.728995  22924.597754  74510.557223  84792.449061   

        中華人民共和国            台湾          大韓民国            香港  
0   8879.652800  17001.319117  14003.463912  35571.828417  
1   5779.035008  16129.033824  15487.798741  32679.542466  
2  24286.335557  22160.730694  19703.287610  43051.070285  
3  23343.856645  25514.944022  19911.776641  45958.701715  
4  29783.074100  26664.797147  21210.299336  53050.094752

In [20]:
X = X.set_index("month")

In [27]:
X = X.set_index("Unnamed: 0")

In [28]:
pca = PCA(n_components=2)
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [29]:
pca.components_[0]

array([ 0.06762001,  0.07708023,  0.76191088,  0.39984508,  0.01564599,
        0.1363264 ,  0.07957638,  0.4732228 ])